/*
 * VmodlNs ManagedObject
 * Joap API
 *
 * The version of the OpenAPI document: vmodl.infra.version.version1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.model.InvalidTransaction;
import org.openapitools.client.model.SuccessfulTransactionResp;
import org.openapitools.client.model.TransactionReq;
import org.springframework.web.client.HttpClientErrorException;
import org.junit.Test;
import org.junit.Ignore;

import static org.junit.Assert.assertNotNull;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DefaultApi
 */
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void transactionPostTest() {
        TransactionReq transactionReq = new TransactionReq();
        transactionReq.setAmount(100);
        SuccessfulTransactionResp response = api.transactionPost(transactionReq);
        assertNotNull(response);
    }
    
    @Test(expected = HttpClientErrorException.class)
    public void transactionPostNegativeTest() {
        TransactionReq transactionReq = new TransactionReq();
        transactionReq.setAmount(-100);
        api.transactionPost(transactionReq);
    }
    
}
