/*
 * VmodlNs ManagedObject
 * Joap API
 *
 * The version of the OpenAPI document: vmodl.infra.version.version1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SuccessfulTransactionResp
 */
public class SuccessfulTransactionRespTest {
    private final SuccessfulTransactionResp model = new SuccessfulTransactionResp();

    /**
     * Model tests for SuccessfulTransactionResp
     */
    @Test
    public void testSuccessfulTransactionResp() {
        // TODO: test SuccessfulTransactionResp
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
